### ISSUE TITLE
PROJECT CHECKLIST 

### ISSUE THREAD

**Issue by n8willis** [theseunbadejo/nsibidi-libre#8]
_This issue tracks checkpoints for the project long term and will be updated by reviewers and QA_

## MILESTONE 1

- [x] Concept for design
- [x] Contract Signing
- [x] GitHub setup complete
- [x] PROTOTYPE HamburgefontsivHAMBURGEFONTSIV!., “space char”
- [x] GoogleFonts Project Template
- [x] Font Building and producing artifacts in Actions tab?
- [x] Checking Fontbakery fails?
- [x] Checking glyph coverage for milestone?

- [x] Team members and reviewers added as collaborators in the repo

### Path direction correction

- [x] Are all characters interpolating? Select all in font tab and fix path direction shift+command+R

### Not necessary in Repo but good for reviewers

- [x] Proofing with Font Proofer or similar tools.
- [x] Are proofs of all characters made? Do you have text set in the font? Are you printing and proofing?
- [x] Are proofs being sent to reviewers for feedback?

### Spacing

- [x] Spacing is tested with spacing strings
- [x] Capitals are spaced to work with lowercase letters

## MILESTONE 2

- [x] 53+ glyphs
- [x] 80+ glyphs, incl A-Z, a-z 0-9, punctuation
- [x] Font Building and producing artifacts in Actions tab?
- [x] Checking Fontbakery fails?

### Path direction correction

- [x] Are all characters interpolating? Select all in font tab and fix path direction shift+command+R

### Not necessary in Repo but good for reviewers

- [x] Proofing with Font Proofer or similar tools.
- [x] Are proofs of all characters made? Do you have text set in the font? Are you printing and proofing?
- [x] Proofs are made with randomized text, and tested at the range of sizes defined in the project brief
- [x] Are proofs being sent to reviewers for feedback?

## MILESTONE 3

- [x] 100+ characters incl. A-Z, a-z, 0-9 in font
- [x] Diacritics (in sets of western euro, Vietnamese, floating, attached)
- [x] Special SSA characters/ Diacritics
- [x] Diacritics are built from combining forms + anchor points
- [x] Diacritics fit into vertical metrics
- [x] Font Building and producing artifacts in Actions tab?
- [x] Checking Fontbakery fails?

### Path direction correction

- [x] Are all characters interpolating? Select all in font tab and fix path direction shift+command+R
- [x] Are all overlaid diacritics using the same path direction?

### Spacing

- [x] Numerals are tabular spaced 

### Not necessary in Repo but good for reviewers

- [x] Proofing with Font Proofer or similar tools.
- [x] Are proofs of all characters made? Do you have text set in the font? Are you printing and proofing?

## MILESTONE 4

- [ ] SSA Google charset ~560 characters x 3 variation axes
- [ ] Font Building and producing artifacts in Actions tab?
- [x] Checking Fontbakery fails?

### Path direction correction

- [x] Are all characters interpolating? Select all in font tab and fix path direction shift+command+R

### Spacing

- [ ] Kerning with Kern On and reviewing kerning (lowercase-lowercase, Capital-lowercase, numerals)

### Not necessary in Repo but good for reviewers

- [ ] Proofing with Font Proofer or similar tools.
- [ ] Are proofs of all characters made? Do you have text set in the font? Are you printing and proofing?

## MILESTONE 5

- [ ] Additional fixing?
- [ ] Fontbakery Bug Fixes
- [ ] Font Building and producing artifacts in Actions tab?
- [ ] Checking Fontbakery fails?

- [ ] Variable axes build?

- [ ] OpenType smart-font features build?

## MILESTONE 6

- [ ] All glyphs complete and known bugs fixed
- [ ] Review with onboarding team

## MILESTONE 7

- [ ] Social media promotion, additional static and animated assets
produced, print-on-demand merchandise available

- [ ] Pull request to Google fonts made? Add font issue to google fonts filed?

**Comment by davelab6** [comment]
Please update to show current status :)

**Comment by n8willis** [comment]
For reference, here are the remaining glyphs from the SSA full set, as Fontbakery reports them:
- [ ] T͟H = T + U+035F + H (Uduk; `udu_Latn` lang)
- [ ] t͟h = t + U+-35F + h (Uduk; `udu_Latn` lang)
- [ ] ◌͟ = U+035F (Uduk; `udu_Latn` lang)
- [ ] Eng + acutecomb (Tafi; `tcd_Latn` lang)
- [ ] Ŧ = U+0166 (Tunisian Darija; `aeb_Latn` lang)
- [ ] ŧ = U+0167 (Tunisian Darija; `aeb_Latn` lang)
- [ ] ᵃ (Teso; `teo_Latn` lang)
- [ ] ᵉ (Teso; `teo_Latn` lang)
- [ ] ᵋ (Teso; `teo_Latn` lang)
- [ ] ᵒ (Teso; `teo_Latn` lang)
- [ ] ᵓ (Teso; `teo_Latn` lang)
- [ ] ᶤ (Teso; `teo_Latn` lang)
- [ ] ᶶ (Teso; `teo_Latn` lang)
- [ ] ⁱ (Teso; `teo_Latn` lang)
- [ ] Ꟈ = (Moro; `mor_Latn` lang)
- [ ] ꟈ = (Moro; `mor_Latn` lang)
- [ ] Eng + gravecomb (Eton; `eto_Latn` lang)
- [ ] Eng + uni0304 (Mano; `mev_Latn` lang)
- [ ] Esh `locl` feature = U+01A9 (Ga; `gaa_Latn` lang)
- [ ] Ezh `locl` feature = U+01B7 (Ga; `gaa_Latn` lang)
- [ ] U+026A + tildecomb (Bondoukou Kulango; `kzc_Latn` lang)
- [ ] U+A7B6 + tildecomb (Bondoukou Kulango; `kzc_Latn` lang)
- [ ] U+A7B7 + tildecomb (Bondoukou Kulango; `kzc_Latn` lang)
- [ ] Eng + uni0308 (Nawdm; `nmz_Latn` lang)
- [ ] U+0254 + uni0328 (Kpelle; `gkp_Latn` lang)
- [ ] U+0186 + uni0328 (Kpelle; `gkp_Latn` lang)
- [ ] Eng + uni030D (Southern Ksi; `kss_Latn` lang)
- [ ] vhook `locl` feature = U+028B (Toma; `tod_Latn` lang)
- [ ] Vhook `locl` feature = U+01B2 (Toma; `tod_Latn` lang)
- [ ] Bhook `locl` feature = U+0181 (Dan; `dnj_Latn` lang)
- [ ] ɤ ramshorn = U+0264 (Dan; `dnj_Latn` lang)
- [ ] ɤ̀ = U+0264 + gravecomb (Dan; `dnj_Latn` lang)
- [ ] ɤ́ = U+0264 + acutecomb (Dan; `dnj_Latn` lang)
- [ ] ɤ̂ = U+0264 + circumflexcomb (Dan; `dnj_Latn` lang)
- [ ] ɤ̄ = U+0264 + macroncomb (Dan; `dnj_Latn` lang)
- [ ] ɤ̋ = U+0264 + doubleacutecomb (Dan; `dnj_Latn` lang)
- [ ] ɤ̏ = U+0264 + doublegravecomb (Dan; `dnj_Latn` lang)
- [ ] Ɤ Ramshorn = U+A7CB (Dan; `dnj_Latn` lang)
- [ ] Ɤ̀ = U+A7CB + gravecomb (Dan; `dnj_Latn` lang)
- [ ] Ɤ́ = U+A7CB + acutecomb (Dan; `dnj_Latn` lang)
- [ ] Ɤ̂ = U+A7CB + circumflexcomb (Dan; `dnj_Latn` lang)
- [ ] Ɤ̄ = U+A7CB + macroncomb (Dan; `dnj_Latn` lang)
- [ ] Ɤ̋ = U+A7CB + doubleacutecomb (Dan; `dnj_Latn` lang)
- [ ] Ɤ̏ = U+A7CB + doublegravecomb (Dan; `dnj_Latn` lang)
- [ ] W̤ = W + U+0324 (Fang; `fan_Latn` lang)
- [ ] w̤ = w + U+0324 (Fang; `fan_Latn` lang)
- [ ] ◌̤ = U+0324 (Fang; `fan_Latn` lang)

Obviously the mark-combination ones are just going to be anchorpoint issues.

I haven't quite chased down info on the various `locl` feature checks. The `locl` feature for Eng was between Sami and African and the decision before was that African should be the default (but the checks assumed Sami was the default). Consequently, I'd presume that if there are other `locl` checks that are assuming that a non-African form is the default, they would get the same handling. 

Will update when I find sources on those.

**Comment by theseunbadejo** [comment]
Thanks for the checklist @n8willis, working on some of these already, should be able to get them all up to date this week/next.

**Comment by n8willis** [comment]
Could I suggest that you split the list into chunks and tackle a small chunk on its own first? That way it'd be easier to see if there is anything else in the build system or bakery checks that has changed. 

Like, the new base-character glyphs that require drawing something new (which possibly includes the glyphs that need locl), the diacritic attachments, the base glyphs that are just modifications of existing glyphs.

I'm not sure I've found all the info needed on the locl ones yet. Maybe you could iron out a few of the diacritic / anchorpoint issues and just merge those. So we can see how the result builds & tests?
